name: Build and release app

on:
  push:
    branches: [ main ]
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
          cache: 'pip'

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false

      - name: Install dependencies
        run: |
          conda install r-base
          conda install r-devtools
          pip install scikit-build
          pip install ./

      - name: Build executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/funki/app/main.py
          mode: standalone
          enable-plugins: tk-inter

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
            build/*.dist/**/*
          include-hidden-files: true
