name: Build docs

on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installing package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install sphinx
        pip install myst_parser
    - name: Building HTML docs
      run: make -C docs html
        
