name: Build and deploy docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installing package and dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install r-base-dev
        sudo apt-get install libtirpc-dev
        pip install scikit-build
        pip install .
        pip install sphinx
        pip install myst_parser
        pip install numba==0.59.0
    - name: Building HTML docs
      run: make docs
    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: docs/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
