name: Build and deploy docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installing package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install sphinx
        pip install myst_parser
    - name: Building HTML docs
      run: make -C docs html
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add docs/
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Docs: Automated build push" -a | exit 0
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate pages artifact
      uses: actions/upload-pages-artifact
      with:
        path: docs/
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
